//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMovie1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieCast
    {
        public int MovieCastID { get; set; }
        public string MovieCastName { get; set; }
        public int PersonRoleID { get; set; }
        public int PersonID { get; set; }
        public int MovieID { get; set; }
    
        public virtual Movie Movie { get; set; }
        public virtual Person Person { get; set; }
        public virtual PersonRole PersonRole { get; set; }
    }
}
