//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMovie1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie_Genre
    {
        public int Movie_GenreID { get; set; }
        public int GenreID { get; set; }
        public int MovieID { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual Movie Movie { get; set; }
    }
}
